name: CI-CD-pipeline-to-AWS-ElasticBeanstalk
env:
  EB_BUCKET_NAME: "flask-app1"
  EB_APPLICATION_NAME: "flaskapp"
  EB_ENVIRONMENT_NAME: "flaskapp-env"
  DEPLOY_PACKAGE_NAME: "flaskapp_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-west-3"
on: 
  push:
    branches: 
      - master 
jobs:
  ci_part: 
    runs-on: ubuntu-latest
    
    steps: 
    - name: Git clone our repo
      uses: actions/checkout@v1
    
    - name: Create ZIP deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
  

